import type { ProductListItem, ProductWithDetails } from "@/types"

export interface FullProductItem extends ProductListItem {
  description: string
  short_description?: string
  images: string[]
  specifications: Record<string, string>
  details: string[]
  shipping_info?: string
  in_stock: boolean
  sku: string
}

export const ALL_PRODUCTS: FullProductItem[] = [
  {
    id: "1",
    name: "Cahier Grand Format 200 Pages A4 Grands Carreaux",
    slug: "cahier-grand-format-200-pages-a4",
    product_type: "stationery",
    price: 29,
    compare_at_price: null,
    is_bestseller: true,
    is_new_arrival: false,
    is_featured: true,
    is_active: true,
    average_rating: 4.8,
    review_count: 128,
    primary_image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&h=1000&fit=crop&q=85",
    images: [
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&h=1000&fit=crop&q=85",
      "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&h=1000&fit=crop&q=85",
      "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=1000&fit=crop&q=85",
    ],
    category_name: "Papeterie",
    brand_name: "Clairefontaine",
    stock: 45,
    in_stock: true,
    sku: "CF-A4-200-GC",
    discount_percentage: null,
    short_description: "Papier vélin velouté 90g ultra-lisse. Idéal pour l'école, le collège et le lycée.",
    description:
      "Le cahier classique Clairefontaine grand format A4 (21x29.7cm) de 200 pages avec réglure Séyès (grands carreaux). Conçu avec le célèbre papier vélin velouté 90 g/m², offrant une douceur d'écriture incomparable, sans bavure ni transparence même à l'encre plume. Couverture pelliculée lavable ultra résistante aux manipulations quotidiennes des élèves.",
    specifications: {
      "Format": "A4 (21 x 29,7 cm)",
      "Nombre de pages": "200 pages (100 feuilles)",
      "Réglure": "Séyès (Grands carreaux)",
      "Grammage": "90 g/m² vélin velouté",
      "Couverture": "Carte pelliculée imperméable",
      "Reliure": "Brochée sans agrafes apparentes",
      "Origine": "France / Certifié PEFC",
    },
    details: [
      "Papier Clairefontaine 90g certifié écologique",
      "Couverture cartonnée pelliculée indéchirable",
      "Encre ne traverse pas le papier",
      "Recommandé par le corps enseignant au Maroc",
    ],
    shipping_info: "Expédié sous 24h ouvrées. Livraison gratuite dès 299 DH partout au Maroc.",
  },
  {
    id: "2",
    name: "Set de Stylos Bille 4 Couleurs BIC Original",
    slug: "set-stylos-bille-4-couleurs-bic",
    product_type: "stationery",
    price: 19,
    compare_at_price: null,
    is_bestseller: true,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    average_rating: 4.7,
    review_count: 312,
    primary_image: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=1000&fit=crop&q=85",
    images: [
      "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=1000&fit=crop&q=85",
      "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=1000&fit=crop&q=85",
    ],
    category_name: "Papeterie",
    brand_name: "BIC",
    stock: 120,
    in_stock: true,
    sku: "BIC-4COL-ORIG",
    discount_percentage: null,
    short_description: "L'incontournable stylo rétractable 4 couleurs (Bleu, Noir, Rouge, Vert) en pointe moyenne 1.0mm.",
    description:
      "Le stylo-bille BIC 4 Couleurs Original est un classique intemporel qui vous permet de changer de couleur d'un simple clic sans jamais changer de stylo. Parfait pour la prise de notes structurée, la relecture et l'organisation scolaire ou professionnelle.",
    specifications: {
      "Pointe": "Moyenne 1,0 mm (trait 0,4 mm)",
      "Couleurs": "Bleu, Noir, Rouge, Vert",
      "Longueur d'écriture": "Jusqu'à 8 km au total (2 km par couleur)",
      "Corps": "Rond bicolore bleu et blanc avec clip",
      "Rechargeable": "Oui",
    },
    details: [
      "Système de sélection par poussoir ultra fluide",
      "Encre haute qualité à séchage rapide",
      "Bille en carbure de tungstène parfaitement sphérique",
    ],
    shipping_info: "En stock. Expédition immédiate depuis notre entrepôt de Casablanca.",
  },
  {
    id: "3",
    name: "Livre Scolaire Mathématiques 3ème Année Collège",
    slug: "livre-mathematiques-3eme-college",
    product_type: "book",
    price: 89,
    compare_at_price: null,
    is_bestseller: true,
    is_new_arrival: false,
    is_featured: true,
    is_active: true,
    average_rating: 4.5,
    review_count: 87,
    primary_image: "https://images.unsplash.com/photo-1609743522471-83c84ce23e32?w=800&h=1000&fit=crop&q=85",
    images: [
      "https://images.unsplash.com/photo-1609743522471-83c84ce23e32?w=800&h=1000&fit=crop&q=85",
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&h=1000&fit=crop&q=85",
    ],
    category_name: "Livres Scolaires",
    brand_name: "Hachette",
    stock: 23,
    in_stock: true,
    sku: "LIV-MATH-3COL",
    discount_percentage: null,
    short_description: "Manuel conforme au programme officiel du Ministère de l'Éducation Nationale marocain.",
    description:
      "Manuel scolaire complet de Mathématiques pour la 3ème année du cycle secondaire collégial. Contient tous les cours théoriques détaillés, des fiches de synthèse, des exercices d'application corrigés pas à pas et des sujets types d'examens régionaux normalisés pour préparer le brevet en toute confiance.",
    specifications: {
      "Niveau": "3ème Année Collège (3AC)",
      "Discipline": "Mathématiques",
      "Langue": "Français / Bilingue (Option Internationale)",
      "Éditeur": "Éditions Scolaires Marocaines",
      "Pages": "240 pages illustrées couleur",
      "Format": "Grand format 20 x 28 cm",
    },
    details: [
      "Conforme au programme officiel en vigueur",
      "Plus de 350 exercices gradués avec solutions",
      "Fiches méthodes d'aide à la résolution de problèmes",
      "Préparation spécifique à l'examen régional",
    ],
    shipping_info: "Livraison sous 24/48h au Maroc. Emballage protecteur cartonné.",
  },
  {
    id: "4",
    name: "Compas Géométrie Métallique Professionnel Maped Stop System",
    slug: "compas-geometrie-professionnel-maped",
    product_type: "school_supply",
    price: 45,
    compare_at_price: null,
    is_bestseller: true,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    average_rating: 4.8,
    review_count: 204,
    primary_image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&h=1000&fit=crop&q=85",
    images: [
      "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&h=1000&fit=crop&q=85",
    ],
    category_name: "Fournitures Scolaires",
    brand_name: "Maped",
    stock: 67,
    in_stock: true,
    sku: "MAP-COMPAS-SS",
    discount_percentage: null,
    short_description: "Compas haute précision avec système de verrouillage des branches et étui de protection.",
    description:
      "Le compas Maped Stop System dispose d'un système breveté exclusif qui bloque l'écartement des branches pour tracer des cercles impeccables sans risque de décalage. Branches métalliques robustes et bague universelle incluse.",
    specifications: {
      "Matériau": "Branches en acier trempé brossé",
      "Système": "Stop System à levier de blocage",
      "Accessoires": "Bague universelle + étui rigide + étui de mines",
      "Diamètre max": "300 mm",
    },
    details: [
      "Blocage immédiat par simple pression du levier",
      "Pointe de sécurité protégée",
      "Boîtier de transport anti-choc",
    ],
    shipping_info: "En stock. Expédition sous 24h.",
  },
  {
    id: "5",
    name: "Cartable Ergonomique Primaire 18L Imperméable Oxford",
    slug: "cartable-ergonomique-primaire-18l",
    product_type: "school_supply",
    price: 249,
    compare_at_price: null,
    is_bestseller: false,
    is_new_arrival: true,
    is_featured: true,
    is_active: true,
    average_rating: 4.7,
    review_count: 43,
    primary_image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=1000&fit=crop&q=85",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=1000&fit=crop&q=85",
    ],
    category_name: "Fournitures Scolaires",
    brand_name: "Oxford",
    stock: 18,
    in_stock: true,
    sku: "CART-PRIM-18L",
    discount_percentage: null,
    short_description: "Cartable léger et renforcé avec bandes réfléchissantes et dos matelassé respirant.",
    description:
      "Conçu spécifiquement pour les élèves du primaire (CP à CM2), ce cartable de 18L combine légèreté et solidité. Structure ergonomique protégeant la colonne vertébrale des enfants, tissu hydrofuge résistant aux intempéries et fond renforcé imperméable.",
    specifications: {
      "Capacité": "18 Litres (accueille les grands classeurs A4)",
      "Poids à vide": "720 grammes",
      "Matériau": "Polyester 600D déperlant haute densité",
      "Sécurité": "Bandes rétro-réfléchissantes 360°",
    },
    details: [
      "Deux grands compartiments intérieurs + poche frontale zippée",
      "Bretelles rembourrées ajustables anti-frottement",
      "Fond rigide protecteur avec patins anti-usure",
    ],
    shipping_info: "Livraison offerte pour ce produit. Paiement à la livraison possible.",
  },
  {
    id: "6",
    name: "Coffret Faber-Castell Crayons de Couleur 36 Nuances Art",
    slug: "faber-castell-crayons-couleur-36",
    product_type: "art",
    price: 129,
    compare_at_price: null,
    is_bestseller: false,
    is_new_arrival: true,
    is_featured: false,
    is_active: true,
    average_rating: 4.9,
    review_count: 156,
    primary_image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=1000&fit=crop&q=85",
    images: [
      "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=1000&fit=crop&q=85",
    ],
    category_name: "Arts & Créativité",
    brand_name: "Faber-Castell",
    stock: 34,
    in_stock: true,
    sku: "FC-COLOR-36TIN",
    discount_percentage: null,
    short_description: "Boîte métal 36 crayons d'art aux pigments intenses et mine incassable SV.",
    description:
      "La référence des crayons de couleur pour artistes en herbe et étudiants en arts plastiques. Mine douce et riche en pigments pour des dégradés subtils et des aplats homogènes. Bois issu de forêts gérées durablement.",
    specifications: {
      "Nombre de crayons": "36 couleurs assorties",
      "Mine": "3.3 mm avec collage spécial SV anti-casse",
      "Forme": "Hexagonale ergonomique",
      "Présentation": "Boîtier métallique collector",
    },
    details: [
      "Pigments ultra lumineux résistants à la lumière",
      "Taille facile sans effritement de la mine",
      "Idéal pour le dessin artistique, croquis et coloriage technique",
    ],
    shipping_info: "En stock. Emballage soigné anti-choc.",
  },
  {
    id: "7",
    name: "Calculatrice Scientifique Casio FX-991ES Plus II",
    slug: "calculatrice-scientifique-casio-fx-82",
    product_type: "school_supply",
    price: 189,
    compare_at_price: null,
    is_bestseller: false,
    is_new_arrival: true,
    is_featured: true,
    is_active: true,
    average_rating: 4.7,
    review_count: 98,
    primary_image: "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=800&h=1000&fit=crop&q=85",
    images: [
      "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=800&h=1000&fit=crop&q=85",
    ],
    category_name: "Fournitures Scolaires",
    brand_name: "Casio",
    stock: 56,
    in_stock: true,
    sku: "CASIO-FX991-ES",
    discount_percentage: null,
    short_description: "Affichage Natural Textbook 2 lignes. Autorisée aux examens du Baccalauréat au Maroc.",
    description:
      "Calculatrice scientifique complète indispensable pour le collège, le lycée (tronc commun, 1ère et 2ème Bac Sciences) et les études supérieures. Écran haute résolution affichant les fractions et racines exactement comme dans les manuels scolaires.",
    specifications: {
      "Fonctions": "417 fonctions scientifiques intégrées",
      "Alimentation": "Double énergie (Solaire + Pile de secours)",
      "Écran": "Natural V.P.A.M. 31 x 96 points",
      "Boîtier": "Capot rigide de protection coulissant",
    },
    details: [
      "Calculs matriciels, vectoriels et équations",
      "Statistiques à 2 variables et régression",
      "Garantie officielle 2 ans",
    ],
    shipping_info: "En stock. Expédition sous 24h avec garantie fabricant.",
  },
  {
    id: "8",
    name: "Agenda Scolaire Journalier 2026 Couverture Cuir",
    slug: "agenda-scolaire-2024-2025-premium",
    product_type: "stationery",
    price: 59,
    compare_at_price: null,
    is_bestseller: false,
    is_new_arrival: true,
    is_featured: false,
    is_active: true,
    average_rating: 4.6,
    review_count: 72,
    primary_image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=1000&fit=crop&q=85",
    images: [
      "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=1000&fit=crop&q=85",
    ],
    category_name: "Bureau",
    brand_name: "Oxford",
    stock: 89,
    in_stock: true,
    sku: "AG-SCOL-2425",
    discount_percentage: null,
    short_description: "1 jour par page avec atlas couleur et calendrier des vacances scolaires marocaines.",
    description:
      "L'agenda scolaire parfait pour organiser son année académique. Grille claire et aérée permettant de noter tous les devoirs, emplois du temps, vacances scolaires marocaines officielles et fiches de révision.",
    specifications: {
      "Période": "Année académique 2026 (11 mois)",
      "Format": "12 x 17 cm compact",
      "Pages": "352 pages papier 80g",
      "Finition": "Coins détachables + signet ruban marque-page",
    },
    details: [
      "Calendrier des vacances scolaires au Maroc",
      "Atlas géographique complet en couleurs",
      "Couverture souple agréable au toucher",
    ],
    shipping_info: "En stock. Livraison express dans tout le Royaume.",
  },
  {
    id: "9",
    name: "Kit Rentrée Scolaire Collège Complet — 25 Pièces",
    slug: "kit-rentree-scolaire-college-complet",
    product_type: "pack",
    price: 299,
    compare_at_price: 449,
    is_bestseller: false,
    is_new_arrival: false,
    is_featured: true,
    is_active: true,
    average_rating: 4.9,
    review_count: 167,
    primary_image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=1000&fit=crop&q=85",
    images: [
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=1000&fit=crop&q=85",
    ],
    category_name: "Kits Scolaires",
    brand_name: "ProExcel Pack",
    stock: 12,
    in_stock: true,
    sku: "KIT-COLLEGE-25P",
    discount_percentage: 33,
    short_description: "Pack tout-en-un certifié conforme à la liste officielle des fournitures de collège.",
    description:
      "Gagnez du temps et faites jusqu'à 35% d'économies avec ce pack prêt à l'emploi conçu par nos libraires. Comprend 6 cahiers grand format, stylos de marque, kit de géométrie complet, surligneurs, crayons de couleur, colle et ciseaux.",
    specifications: {
      "Contenu": "25 pièces de marques reconnues (Clairefontaine, Maped, BIC, Stabilo)",
      "Niveau": "Collège (1AC, 2AC, 3AC)",
      "Économie": "Plus de 150 DH par rapport à l'achat unitaire",
    },
    details: [
      "6x Cahiers grand format 200p Clairefontaine",
      "1x Kit géométrie 4 pièces incassable Maped",
      "1x Set 4 stylos BIC + 4 surligneurs Stabilo",
      "1x Trousse offerte avec le pack",
    ],
    shipping_info: "Livraison gratuite partout au Maroc. Quantités limitées.",
  },
  {
    id: "10",
    name: "Stabilo Boss Original Surligneur Pochette de 8 Couleurs",
    slug: "stabilo-boss-surligneur-8-couleurs",
    product_type: "stationery",
    price: 39,
    compare_at_price: 55,
    is_bestseller: false,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    average_rating: 4.8,
    review_count: 289,
    primary_image: "https://images.unsplash.com/photo-1585336261026-7f8a9e46a782?w=800&h=1000&fit=crop&q=85",
    images: [
      "https://images.unsplash.com/photo-1585336261026-7f8a9e46a782?w=800&h=1000&fit=crop&q=85",
    ],
    category_name: "Papeterie",
    brand_name: "Stabilo",
    stock: 78,
    in_stock: true,
    sku: "STAB-BOSS-8SET",
    discount_percentage: 29,
    short_description: "Pochette de 8 surligneurs fluo et pastel avec technologie anti-dessèchement 4h.",
    description:
      "Le surligneur n°1 mondial depuis 1971. Encre universelle à base d'eau qui ne traverse pas le papier. Pointe biseautée permettant deux largeurs de tracé (2 et 5 mm).",
    specifications: {
      "Pointe": "Biseautée 2 mm et 5 mm",
      "Technologie": "Anti-Dry-Out (reste ouvert 4h sans sécher)",
      "Couleurs": "8 couleurs vives et intenses",
    },
    details: [
      "Idéal pour ficher ses cours et mémoriser",
      "Rechargeable avec les recharges Stabilo",
    ],
    shipping_info: "En stock. Expédition immédiate.",
  },
  {
    id: "11",
    name: "Classeur A4 Polypropylène 4 Anneaux Oxford 40mm",
    slug: "oxford-classeur-a4-4-anneaux-40mm",
    product_type: "stationery",
    price: 49,
    compare_at_price: 69,
    is_bestseller: false,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    average_rating: 4.4,
    review_count: 54,
    primary_image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=1000&fit=crop&q=85",
    images: [
      "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=1000&fit=crop&q=85",
    ],
    category_name: "Bureau",
    brand_name: "Oxford",
    stock: 45,
    in_stock: true,
    sku: "OX-CLAS-A4-40",
    discount_percentage: 29,
    short_description: "Classeur rigide en plastique résistant avec étiquette de dos personnalisable.",
    description:
      "Classeur d'archivage et de cours grand format A4. Mécanisme 4 anneaux en D haute capacité (jusqu'à 250 feuilles) garantissant un alignement parfait des documents et pochettes plastiques.",
    specifications: {
      "Format": "A4 Maxi (26 x 32 cm)",
      "Dos": "40 mm (capacité 250 feuilles)",
      "Anneaux": "4 anneaux en D 30 mm",
      "Matière": "Polypropylène indéchirable et lavable",
    },
    details: [
      "Compatible avec les pochettes perforées grand format",
      "Porte-étiquette au dos avec étiquette réversible",
    ],
    shipping_info: "En stock.",
  },
  {
    id: "12",
    name: "Manuel Scolaire Français 1ère Année Baccalauréat",
    slug: "livre-francais-1ere-bac",
    product_type: "book",
    price: 69,
    compare_at_price: 89,
    is_bestseller: false,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    average_rating: 4.6,
    review_count: 33,
    primary_image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&h=1000&fit=crop&q=85",
    images: [
      "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&h=1000&fit=crop&q=85",
    ],
    category_name: "Livres Scolaires",
    brand_name: "Hachette",
    stock: 30,
    in_stock: true,
    sku: "LIV-FR-1BAC",
    discount_percentage: 22,
    short_description: "Étude des 3 œuvres au programme régional (La Boîte à Merveilles, Antigone, Le Dernier Jour).",
    description:
      "L'ouvrage de référence pour réussir l'examen régional de français 1ère Bac. Analyses littéraires complètes, axes de lecture, fiches de vocabulaire et figures de style, sujets d'expression écrite guidés et corrigés d'examens précédents.",
    specifications: {
      "Niveau": "1ère Année du Baccalauréat (Toutes filières)",
      "Matière": "Français (Examen Régional)",
      "Pages": "210 pages",
    },
    details: [
      "Résumé scène par scène / chapitre par chapitre",
      "Quiz de compréhension et fiches de synthèse",
      "Méthodologie détaillée de la production écrite",
    ],
    shipping_info: "Livraison rapide sous 24/48h au Maroc.",
  },
  {
    id: "13",
    name: "Trousse Scolaire Double Compartiment Renforcée",
    slug: "trousse-scolaire-double-compartiment",
    product_type: "school_supply",
    price: 35,
    compare_at_price: 49,
    is_bestseller: true,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    average_rating: 4.7,
    review_count: 89,
    primary_image: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=1000&fit=crop&q=85",
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=1000&fit=crop&q=85"],
    category_name: "Fournitures Scolaires",
    brand_name: "Maped",
    stock: 65,
    in_stock: true,
    sku: "MAP-TROUSSE-2C",
    discount_percentage: 28,
    short_description: "Trousse zippée spacieuse avec doublure lavable et tirettes métalliques robustes.",
    description: "Trousse à deux grands compartiments indépendants pour organiser stylos, crayons, feutres, ciseaux et colle.",
    specifications: { "Dimensions": "22 x 8 x 8 cm", "Matière": "Polyester 600D lavable", "Fermeture": "Zips haute résistance" },
    details: ["Deux compartiments séparés", "Tissu imperméable facile à nettoyer"],
    shipping_info: "En stock. Expédition immédiate.",
  },
  {
    id: "14",
    name: "Règle Plate Incassable 30 cm Maped Twist'n Flex",
    slug: "regle-plate-incassable-30cm-maped",
    product_type: "school_supply",
    price: 15,
    compare_at_price: null,
    is_bestseller: false,
    is_new_arrival: true,
    is_featured: false,
    is_active: true,
    average_rating: 4.9,
    review_count: 145,
    primary_image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&h=1000&fit=crop&q=85",
    images: ["https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&h=1000&fit=crop&q=85"],
    category_name: "Fournitures Scolaires",
    brand_name: "Maped",
    stock: 140,
    in_stock: true,
    sku: "MAP-REGLE-TF30",
    discount_percentage: null,
    short_description: "Règle souple incassable et flexible sans phtalates. Ne se casse jamais dans le cartable.",
    description: "La célèbre règle flexible Twist'n Flex de Maped se tord à l'infini et reprend sa forme sans jamais casser.",
    specifications: { "Longueur": "30 cm", "Graduation": "Millimétrée recto-verso", "Matériau": "Matériau souple incassable" },
    details: ["Résiste à toutes les torsions", "Graduation haute précision ineffaçable"],
    shipping_info: "En stock. Expédition sous 24h.",
  },
  {
    id: "15",
    name: "Paquet de 500 Feuilles Papier A4 80g Extra Blanc",
    slug: "paquet-500-feuilles-papier-a4-clairefontaine",
    product_type: "stationery",
    price: 55,
    compare_at_price: 65,
    is_bestseller: true,
    is_new_arrival: false,
    is_featured: true,
    is_active: true,
    average_rating: 4.8,
    review_count: 210,
    primary_image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&h=1000&fit=crop&q=85",
    images: ["https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&h=1000&fit=crop&q=85"],
    category_name: "Papeterie",
    brand_name: "Clairefontaine",
    stock: 90,
    in_stock: true,
    sku: "CF-PAP-A4-500",
    discount_percentage: 15,
    short_description: "Ramette 500 feuilles ultra-blanches pour impression laser, jet d'encre et écriture.",
    description: "Papier multi-usages de haute blancheur CIE 168. Idéal pour les rapports, devoirs et impressions quotidiennes.",
    specifications: { "Format": "A4 (21 x 29,7 cm)", "Grammage": "80 g/m²", "Feuilles": "500 feuilles" },
    details: ["Blancheur exceptionnelle", "Certifié écologique FSC et Ecolabel"],
    shipping_info: "En stock à Casablanca.",
  },
  {
    id: "16",
    name: "Livre Le Petit Prince — Antoine de Saint-Exupéry",
    slug: "livre-le-petit-prince-saint-exupery",
    product_type: "book",
    price: 45,
    compare_at_price: null,
    is_bestseller: true,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    average_rating: 5.0,
    review_count: 420,
    primary_image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&h=1000&fit=crop&q=85",
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&h=1000&fit=crop&q=85"],
    category_name: "Livres",
    brand_name: "Hachette",
    stock: 50,
    in_stock: true,
    sku: "LIV-PETIT-PRINCE",
    discount_percentage: null,
    short_description: "Édition intégrale avec illustrations originales de l'auteur en couleurs.",
    description: "Chef-d'œuvre universel de la littérature française, au programme scolaire et incontournable pour tous les âges.",
    specifications: { "Auteur": "Antoine de Saint-Exupéry", "Éditeur": "Gallimard Folio", "Pages": "128 pages" },
    details: ["Texte intégral", "Aquarelles originales restaurées"],
    shipping_info: "En stock. Livraison 24h.",
  },
  {
    id: "17",
    name: "Set de Peinture Gouache 12 Tubes 20ml Faber-Castell",
    slug: "set-peinture-gouache-12-tubes-faber-castell",
    product_type: "art",
    price: 85,
    compare_at_price: 110,
    is_bestseller: false,
    is_new_arrival: true,
    is_featured: false,
    is_active: true,
    average_rating: 4.8,
    review_count: 67,
    primary_image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=1000&fit=crop&q=85",
    images: ["https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=1000&fit=crop&q=85"],
    category_name: "Arts & Créativité",
    brand_name: "Faber-Castell",
    stock: 38,
    in_stock: true,
    sku: "FC-GOUACHE-12T",
    discount_percentage: 22,
    short_description: "Gouache fine opaque aux couleurs vives avec pinceau et palette inclus.",
    description: "Gouache de qualité supérieure hautement pigmentée, idéale pour les arts plastiques et les projets artistiques à l'école.",
    specifications: { "Contenu": "12 tubes de 20ml + 1 pinceau", "Type": "Gouache à l'eau opaque lavable" },
    details: ["Couleurs miscibles à l'infini", "Lavable sur la plupart des tissus"],
    shipping_info: "En stock. Emballage protecteur.",
  },
  {
    id: "18",
    name: "Organiseur de Bureau Métallique Multifonctions 6 Compartiments",
    slug: "organiseur-bureau-metallique-6-compartiments",
    product_type: "office",
    price: 79,
    compare_at_price: 99,
    is_bestseller: false,
    is_new_arrival: true,
    is_featured: false,
    is_active: true,
    average_rating: 4.6,
    review_count: 48,
    primary_image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=1000&fit=crop&q=85",
    images: ["https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=1000&fit=crop&q=85"],
    category_name: "Bureau",
    brand_name: "Oxford",
    stock: 42,
    in_stock: true,
    sku: "BUR-ORG-METAL6",
    discount_percentage: 20,
    short_description: "Organiseur grillagé en métal noir avec tiroir coulissant et porte-stylos.",
    description: "Gardez votre espace de travail ou de révision parfaitement ordonné grâce à cet organiseur de bureau polyvalent.",
    specifications: { "Dimensions": "22 x 14 x 13 cm", "Matériau": "Métal mesh noir traité anti-rouille" },
    details: ["6 compartiments + 1 tiroir", "Patins antidérapants sous la base"],
    shipping_info: "En stock.",
  },
  {
    id: "19",
    name: "Pack Lycée Scientifique Complet — Fournitures & Cahiers",
    slug: "pack-lycee-scientifique-complet",
    product_type: "pack",
    price: 349,
    compare_at_price: 480,
    is_bestseller: true,
    is_new_arrival: false,
    is_featured: true,
    is_active: true,
    average_rating: 4.9,
    review_count: 114,
    primary_image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=1000&fit=crop&q=85",
    images: ["https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=1000&fit=crop&q=85"],
    category_name: "Kits Scolaires",
    brand_name: "ProExcel Pack",
    stock: 20,
    in_stock: true,
    sku: "KIT-LYCEE-SCI",
    discount_percentage: 27,
    short_description: "Pack tout-en-un pour Tronc Commun, 1ère Bac et 2ème Bac Sciences.",
    description: "Comprend les grands cahiers Clairefontaine 200p et 100p, classeurs Oxford, calculatrice scientifique Casio, surligneurs Stabilo et stylos Pilot.",
    specifications: { "Contenu": "30 articles de marques leaders", "Niveau": "Lycée Scientifique et Technique" },
    details: ["Économie garantie de plus de 130 DH", "Conforme aux recommandations des professeurs"],
    shipping_info: "Livraison 100% offerte partout au Maroc.",
  },
  {
    id: "20",
    name: "Stylo Roller Gel Pilot G2 Noir 0.7mm — Lot de 3",
    slug: "stylo-roller-gel-pilot-g2-lot-de-3",
    product_type: "stationery",
    price: 42,
    compare_at_price: null,
    is_bestseller: false,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    average_rating: 4.9,
    review_count: 180,
    primary_image: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=1000&fit=crop&q=85",
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=1000&fit=crop&q=85"],
    category_name: "Papeterie",
    brand_name: "Pilot",
    stock: 75,
    in_stock: true,
    sku: "PILOT-G2-3PACK",
    discount_percentage: null,
    short_description: "Encre gel fluide ultra-douce avec grip ergonomique en caoutchouc.",
    description: "Le stylo roller gel référence pour une écriture sans effort et un séchage ultra-rapide.",
    specifications: { "Pointe": "Moyenne 0.7 mm (trait 0.39 mm)", "Couleur": "Noir intense" },
    details: ["Rechargeable", "Grip de confort anti-fatigue"],
    shipping_info: "En stock.",
  },
  {
    id: "21",
    name: "Dictionnaire Le Robert & Collins Français-Arabe / Arabe-Français",
    slug: "dictionnaire-robert-collins-francais-arabe",
    product_type: "book",
    price: 140,
    compare_at_price: null,
    is_bestseller: false,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    average_rating: 4.8,
    review_count: 92,
    primary_image: "https://images.unsplash.com/photo-1609743522471-83c84ce23e32?w=800&h=1000&fit=crop&q=85",
    images: ["https://images.unsplash.com/photo-1609743522471-83c84ce23e32?w=800&h=1000&fit=crop&q=85"],
    category_name: "Livres",
    brand_name: "Hachette",
    stock: 28,
    in_stock: true,
    sku: "DICT-FR-AR-ROB",
    discount_percentage: null,
    short_description: "Plus de 65 000 mots et expressions avec guide de grammaire et prononciation.",
    description: "Ouvrage complet et moderne recommandé pour les élèves du collège, lycée et études supérieures.",
    specifications: { "Éditeur": "Le Robert", "Pages": "850 pages reliées", "Format": "Poche compact" },
    details: ["Vocabulaire actuel", "Annexes culturelles et conjugaisons"],
    shipping_info: "Livraison rapide au Maroc.",
  },
  {
    id: "22",
    name: "Bloc de Dessin Canson A3 200g Grain Fin 20 Feuilles",
    slug: "bloc-dessin-canson-a3-200g",
    product_type: "art",
    price: 65,
    compare_at_price: 80,
    is_bestseller: false,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    average_rating: 4.9,
    review_count: 104,
    primary_image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=1000&fit=crop&q=85",
    images: ["https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=1000&fit=crop&q=85"],
    category_name: "Arts & Créativité",
    brand_name: "Clairefontaine",
    stock: 40,
    in_stock: true,
    sku: "CAN-DESS-A3-200",
    discount_percentage: 18,
    short_description: "Papier à grain fin résistant aux gommages répétés, idéal pour crayon, fusain et gouache.",
    description: "Le papier dessin Canson iconique reconnu pour son blanc naturel et sa texture équilibrée.",
    specifications: { "Format": "A3 (29.7 x 42 cm)", "Grammage": "200 g/m²", "Feuilles": "20 feuilles détachables" },
    details: ["Grain fin régulier", "Sans acide pour une conservation optimale"],
    shipping_info: "En stock.",
  },
  {
    id: "23",
    name: "Ciseaux Scolaires Ergonomiques 13cm Bouts Ronds Maped",
    slug: "ciseaux-scolaires-bouts-ronds-maped",
    product_type: "school_supply",
    price: 18,
    compare_at_price: null,
    is_bestseller: false,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    average_rating: 4.7,
    review_count: 88,
    primary_image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&h=1000&fit=crop&q=85",
    images: ["https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&h=1000&fit=crop&q=85"],
    category_name: "Fournitures Scolaires",
    brand_name: "Maped",
    stock: 110,
    in_stock: true,
    sku: "MAP-CIS-13BR",
    discount_percentage: null,
    short_description: "Lames en acier inoxydable avec bouts arrondis de sécurité pour enfants.",
    description: "Anneaux ergonomiques soft 3D adaptés aux petites mains pour une coupe nette et sécurisée dès l'école primaire.",
    specifications: { "Longueur": "13 cm", "Sécurité": "Bouts ronds sécurisés", "Matériau": "Inox brossé et plastique soft" },
    details: ["Confort de coupe optimal", "Recommandé pour l'école primaire"],
    shipping_info: "En stock.",
  },
  {
    id: "24",
    name: "Pochette de 100 Pochettes Plastiques Perforées A4 Transparentes",
    slug: "pochette-100-pochettes-perforees-a4",
    product_type: "office",
    price: 32,
    compare_at_price: null,
    is_bestseller: false,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    average_rating: 4.6,
    review_count: 76,
    primary_image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=1000&fit=crop&q=85",
    images: ["https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=1000&fit=crop&q=85"],
    category_name: "Bureau",
    brand_name: "Oxford",
    stock: 95,
    in_stock: true,
    sku: "OX-POCH-A4-100",
    discount_percentage: null,
    short_description: "Pochettes lisses transparentes haute résistance 80 microns avec bande renforcée.",
    description: "Indispensables pour le classement des cours, fiches de révision et documents administratifs.",
    specifications: { "Format": "A4 standard", "Épaisseur": "80 microns", "Quantité": "Paquet de 100 pochettes" },
    details: ["Bande de perforation 11 trous universelle", "Plastique anti-reflets transparent"],
    shipping_info: "En stock.",
  },
]

// ── Homepage section distinct subsets ──────────────────────────
export const SAMPLE_BESTSELLERS: ProductListItem[] = [
  ALL_PRODUCTS[0], // Cahier Clairefontaine 200p
  ALL_PRODUCTS[1], // Stylos BIC 4 Couleurs
  ALL_PRODUCTS[2], // Livre Mathématiques 3ème Collège
  ALL_PRODUCTS[3], // Compas Géométrie Maped
]

export const SAMPLE_NEW_ARRIVALS: ProductListItem[] = [
  ALL_PRODUCTS[4], // Cartable Ergonomique Oxford
  ALL_PRODUCTS[5], // Coffret Faber-Castell 36 Nuances
  ALL_PRODUCTS[6], // Calculatrice Casio FX-991
  ALL_PRODUCTS[7], // Agenda Scolaire Journalier
]

export const SAMPLE_OFFERS: ProductListItem[] = [
  ALL_PRODUCTS[8],  // Kit Rentrée Collège (-33%)
  ALL_PRODUCTS[9],  // Stabilo Boss 8 Couleurs (-29%)
  ALL_PRODUCTS[10], // Classeur Oxford (-29%)
  ALL_PRODUCTS[11], // Manuel Français 1ère Bac (-22%)
]

// ── Helpers ───────────────────────────────────────────────────
export function getProductBySlug(slug: string): FullProductItem | undefined {
  return ALL_PRODUCTS.find((p) => p.slug === slug)
}

export function getRelatedProducts(currentSlug: string, categoryName?: string | null, limit = 4): ProductListItem[] {
  const others = ALL_PRODUCTS.filter((p) => p.slug !== currentSlug)
  if (categoryName) {
    const sameCat = others.filter((p) => p.category_name === categoryName)
    if (sameCat.length >= limit) return sameCat.slice(0, limit)
    const rest = others.filter((p) => p.category_name !== categoryName)
    return [...sameCat, ...rest].slice(0, limit)
  }
  return others.slice(0, limit)
}

export function getProductsByCategory(categorySlug: string): FullProductItem[] {
  const mapping: Record<string, string> = {
    "livres-scolaires": "Livres Scolaires",
    "livres": "Livres",
    "papeterie": "Papeterie",
    "fournitures-scolaires": "Fournitures Scolaires",
    "bureau": "Bureau",
    "arts-creativite": "Arts & Créativité",
    "kits-scolaires": "Kits Scolaires",
  }

  const categoryName = mapping[categorySlug]
  if (!categoryName) return ALL_PRODUCTS

  return ALL_PRODUCTS.filter(
    (p) => p.category_name?.toLowerCase() === categoryName.toLowerCase()
  )
}
